import { createContext, useContext, useState, type ReactNode } from 'react';

export type Lang = 'en' | 'gu' | 'ta' | 'kn';

export const langLabels: Record<Lang, string> = {
  en: 'EN',
  gu: 'ગુ',
  ta: 'த',
  kn: 'ಕ',
};

export const langNames: Record<Lang, string> = {
  en: 'English',
  gu: 'ગુજરાતી',
  ta: 'தமிழ்',
  kn: 'ಕನ್ನಡ',
};

// Core UI strings used across the site
export const t: Record<Lang, Record<string, string>> = {
  en: {
    products: 'Products',
    cropGuide: 'Crop Guide',
    about: 'About',
    contact: 'Contact',
    contactUs: 'Contact Us',
    heroTitle1: 'Next-Generation Bio-Organic',
    heroTitle2: 'Crop Solutions',
    heroDesc: 'High-performance, eco-friendly agro-inputs engineered to maximise your yield at a lower cost — backed by continuous R&D and on-ground expert support for progressive farmers.',
    exploreProducts: 'Explore Products',
    findByCrop: 'Become a Dealer',
    nocBadge: 'FCO Approved · 🇮🇳 Made in India',
    ourRange: 'Our Range',
    sixCategories: 'Product Category',
    topProducts: 'Featured Products',
    flagshipSolutions: 'Trusted by farmers across India',
    viewAll: 'View all products',
    cropSolutions: 'Crop Solutions',
    whatsYourCrop: "What's your crop?",
    cropDesc: 'Select your crop and get expert product recommendations tailored to your needs.',
    fullCropGuide: 'Full Crop Guide',
    whyUs: 'The Pratham Agro Advantage',
    builtForFarmers: 'Why Choose Us',
    becomeDealer: 'Become a Dealer',
    getInTouch: 'Get in touch',
    sendMessage: 'Send Message',
    viewDetails: 'View details',
    browse: 'Browse',
    bestSeller: 'Best Seller',
    keyBenefits: 'Key Benefits',
    dosage: 'Application & Dosage',
    suitableCrops: 'Suitable Crops',
    packSizes: 'Pack Sizes',
    ingredients: 'Active Ingredients',
    sendInquiry: 'Send Inquiry',
    backToProducts: '← Back to Products',
    findRightProduct: 'Find the right product',
    byCrop: 'By Crop',
    byProblem: 'By Problem',
    recommended: 'recommended',
    talkToExpert: 'Talk to Expert',
    generalInquiry: 'General Inquiry',
    dealerReg: 'Become a Dealer',
    distributor: 'Distributor',
  },
  gu: {
    products: 'ઉત્પાદનો',
    cropGuide: 'પાક માર્ગદર્શિકા',
    about: 'અમારા વિશે',
    contact: 'સંપર્ક',
    contactUs: 'સંપર્ક કરો',
    heroTitle1: 'નવી પેઢીના બાયો-ઓર્ગેનિક',
    heroTitle2: 'પાક ઉકેલ',
    heroDesc: 'ઉચ્ચ કામગીરી, ઇકો-ફ્રેન્ડ્લી એગ્રો-ઇનપુટ્સ — ઓછા ખર્ચે વધુ ઉત્પાદન. સતત R&D અને નિષ્ણાત ક્ષેત્ર સહાય સાથે.',
    exploreProducts: 'ઉત્પાદનો જુઓ',
    findByCrop: 'પાક દ્વારા શોધો',
    nocBadge: 'FCO મંજૂર · પૅન ઇન્ડિયા અધિકૃત',
    ourRange: 'અમારી શ્રેણી',
    sixCategories: 'ઉત્પાદન કેટેગરી',
    topProducts: 'ટોચના ઉત્પાદનો',
    flagshipSolutions: 'અમારા પ્રમુખ ઉત્પાદનો',
    viewAll: 'તમામ ઉત્પાદનો',
    cropSolutions: 'પાક ઉકેલ',
    whatsYourCrop: 'તમારો પાક કયો છે?',
    cropDesc: 'તમારો પાક પસંદ કરો અને નિષ્ણાત ઉત્પાદન ભલામણ મેળવો.',
    fullCropGuide: 'સંપૂર્ણ પાક માર્ગદર્શિકા',
    whyUs: 'શા માટે પ્રથમ એગ્રો',
    builtForFarmers: 'ભારતના ખેડૂતો માટે',
    becomeDealer: 'ડીલર બનો',
    getInTouch: 'સંપર્ક કરો',
    sendMessage: 'સંદેશ મોકલો',
    viewDetails: 'વિગતો જુઓ',
    browse: 'બ્રાઉઝ',
    bestSeller: 'બેસ્ટ સેલર',
    keyBenefits: 'મુખ્ય ફાયદા',
    dosage: 'ઉપયોગ અને ડોઝ',
    suitableCrops: 'યોગ્ય પાક',
    packSizes: 'પ્રેક સાઇઝ',
    ingredients: 'સક્રિય ઘટકો',
    sendInquiry: 'તપાસ મોકલો',
    backToProducts: '← ઉત્પાદનો પર પાછા',
    findRightProduct: 'યોગ્ય ઉત્પાદન શોધો',
    byCrop: 'પાક દ્વારા',
    byProblem: 'સમસ્યા દ્વારા',
    recommended: 'ભલામણ',
    talkToExpert: 'નિષ્ણાત સાથે વાત',
    generalInquiry: 'સામાન્ય પ્રશ્ન',
    dealerReg: 'ડીલર નોંધણી',
    distributor: 'ડિસ્ટ્રિબ્યુટર',
  },
  ta: {
    products: 'தயாரிப்புகள்',
    cropGuide: 'பயிர் வழிகாட்டி',
    about: 'எங்களைப் பற்றி',
    contact: 'தொடர்பு',
    contactUs: 'தொடர்பு கொள்ளுங்கள்',
    heroTitle1: 'இயற்கையின் அறிவியல்',
    heroTitle2: 'இந்திய விவசாயத்திற்காக',
    heroDesc: 'அரசு-அங்கீகரிக்கப்பட்ட உயிர் தூண்டிகள், பூஞ்சைக்கொல்லிகள் & வளர்ச்சி மேம்படுத்திகள் — குஜராத்தில் தயாரிக்கப்பட்டது.',
    exploreProducts: 'தயாரிப்புகளை காண்க',
    findByCrop: 'பயிர் மூலம் தேடுங்கள்',
    nocBadge: 'FCO அங்கீகரிக்கப்பட்டது · அகில இந்திய அங்கீகாரம்',
    ourRange: 'எங்கள் வரம்பு',
    sixCategories: 'ஆறு சிறப்பு வகைகள்',
    topProducts: 'சிறந்த தயாரிப்புகள்',
    flagshipSolutions: 'எங்கள் முக்கிய தீர்வுகள்',
    viewAll: 'அனைத்து தயாரிப்புகளும்',
    cropSolutions: 'பயிர் தீர்வுகள்',
    whatsYourCrop: 'உங்கள் பயிர் என்ன?',
    cropDesc: 'உங்கள் பயிரை தேர்வு செய்து நிபுணர் பரிந்துரைகளை பெறுங்கள்.',
    fullCropGuide: 'முழு பயிர் வழிகாட்டி',
    whyUs: 'ஏன் பிரதம் அக்ரோ',
    builtForFarmers: 'இந்திய விவசாயிகளுக்காக',
    becomeDealer: 'டீலராக ஆகுங்கள்',
    getInTouch: 'தொடர்பு கொள்ளுங்கள்',
    sendMessage: 'செய்தி அனுப்பு',
    viewDetails: 'விவரங்கள் காண்க',
    browse: 'உலாவு',
    bestSeller: 'சிறந்த விற்பனை',
    keyBenefits: 'முக்கிய நன்மைகள்',
    dosage: 'பயன்பாடு & மோதிரம்',
    suitableCrops: 'பொருத்தமான பயிர்கள்',
    packSizes: 'பேக் அளவுகள்',
    ingredients: 'செயல் பொருட்கள்',
    sendInquiry: 'விசாரணை அனுப்பு',
    backToProducts: '← தயாரிப்புகளுக்கு திரும்பு',
    findRightProduct: 'சரியான தயாரிப்பை கண்டுபிடி',
    byCrop: 'பயிர் மூலம்',
    byProblem: 'பிரச்சனை மூலம்',
    recommended: 'பரிந்துரைக்கப்பட்டது',
    talkToExpert: 'நிபுணரிடம் பேசு',
    generalInquiry: 'பொது விசாரணை',
    dealerReg: 'டீலர் பதிவு',
    distributor: 'விநியோகஸ்தர்',
  },
  kn: {
    products: 'ಉತ್ಪನ್ನಗಳು',
    cropGuide: 'ಬೆಳೆ ಮಾರ್ಗದರ್ಶಿ',
    about: 'ನಮ್ಮ ಬಗ್ಗೆ',
    contact: 'ಸಂಪರ್ಕ',
    contactUs: 'ಸಂಪರ್ಕಿಸಿ',
    heroTitle1: 'ಪ್ರಕೃತಿಯ ವಿಜ್ಞಾನ',
    heroTitle2: 'ಭಾರತೀಯ ಕೃಷಿಗಾಗಿ',
    heroDesc: 'ಸರ್ಕಾರ-ಅನುಮೋದಿತ ಬಯೋ ಸ್ಟಿಮ್ಯುಲೆಂಟ್‌ಗಳು, ಶಿಲೀಂಧ್ರನಾಶಕಗಳು & ಬೆಳವಣಿಗೆ ವರ್ಧಕಗಳು — ಗುಜರಾತ್‌ನಲ್ಲಿ ತಯಾರಿಸಲಾಗಿದೆ.',
    exploreProducts: 'ಉತ್ಪನ್ನಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    findByCrop: 'ಬೆಳೆಯಿಂದ ಹುಡುಕಿ',
    nocBadge: 'FCO ಅನುಮೋದಿತ · ಅಖಿಲ ಭಾರತ ಅಧಿಕೃತ',
    ourRange: 'ನಮ್ಮ ಶ್ರೇಣಿ',
    sixCategories: 'ಆರು ವಿಶೇಷ ವರ್ಗಗಳು',
    topProducts: 'ಉನ್ನತ ಉತ್ಪನ್ನಗಳು',
    flagshipSolutions: 'ನಮ್ಮ ಪ್ರಮುಖ ಪರಿಹಾರಗಳು',
    viewAll: 'ಎಲ್ಲಾ ಉತ್ಪನ್ನಗಳು',
    cropSolutions: 'ಬೆಳೆ ಪರಿಹಾರಗಳು',
    whatsYourCrop: 'ನಿಮ್ಮ ಬೆಳೆ ಯಾವುದು?',
    cropDesc: 'ನಿಮ್ಮ ಬೆಳೆ ಆಯ್ಕೆ ಮಾಡಿ ಮತ್ತು ತಜ್ಞ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ.',
    fullCropGuide: 'ಸಂಪೂರ್ಣ ಬೆಳೆ ಮಾರ್ಗದರ್ಶಿ',
    whyUs: 'ಏಕೆ ಪ್ರಥಮ್ ಅಗ್ರೋ',
    builtForFarmers: 'ಭಾರತದ ರೈತರಿಗಾಗಿ',
    becomeDealer: 'ಡೀಲರ್ ಆಗಿ',
    getInTouch: 'ಸಂಪರ್ಕಿಸಿ',
    sendMessage: 'ಸಂದೇಶ ಕಳುಹಿಸಿ',
    viewDetails: 'ವಿವರಗಳನ್ನು ನೋಡಿ',
    browse: 'ಬ್ರೌಸ್ ಮಾಡಿ',
    bestSeller: 'ಅತ್ಯುತ್ತಮ ಮಾರಾಟ',
    keyBenefits: 'ಮುಖ್ಯ ಪ್ರಯೋಜನಗಳು',
    dosage: 'ಬಳಕೆ & ಡೋಸ್',
    suitableCrops: 'ಸೂಕ್ತ ಬೆಳೆಗಳು',
    packSizes: 'ಪ್ಯಾಕ್ ಗಾತ್ರಗಳು',
    ingredients: 'ಸಕ್ರಿಯ ಪದಾರ್ಥಗಳು',
    sendInquiry: 'ವಿಚಾರಣೆ ಕಳುಹಿಸಿ',
    backToProducts: '← ಉತ್ಪನ್ನಗಳಿಗೆ ಹಿಂತಿರುಗಿ',
    findRightProduct: 'ಸರಿಯಾದ ಉತ್ಪನ್ನ ಹುಡುಕಿ',
    byCrop: 'ಬೆಳೆಯಿಂದ',
    byProblem: 'ಸಮಸ್ಯೆಯಿಂದ',
    recommended: 'ಶಿಫಾರಸು',
    talkToExpert: 'ತಜ್ಞರೊಂದಿಗೆ ಮಾತನಾಡಿ',
    generalInquiry: 'ಸಾಮಾನ್ಯ ವಿಚಾರಣೆ',
    dealerReg: 'ಡೀಲರ್ ನೋಂದಣಿ',
    distributor: 'ವಿತರಕ',
  },
};

interface LangCtx { lang: Lang; setLang: (l: Lang) => void; tr: (key: string) => string; }
const LangContext = createContext<LangCtx>({ lang: 'en', setLang: () => {}, tr: k => k });

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('en');
  const tr = (key: string) => t[lang][key] ?? t['en'][key] ?? key;
  return <LangContext.Provider value={{ lang, setLang, tr }}>{children}</LangContext.Provider>;
}

export const useLang = () => useContext(LangContext);
